export type {
  IDynamicObject,
  ICreateFirebaseUser,
  ILoginUser,
  IPresignedPutUrlRequest,
  IPresignedPutUrlsRequest,
  IPresignedGetUrlsRequest,
  IStandardSubjectQuery,
  IScoreRating,
  ISubjectGraphData,
  ITarget,
  IFunctionProps,
  IPosition,
  IToast,
  ToastType,
  ICourseBase,
  IMaterialInfo,
  IQuestionBase,
  ITestPaperBase,
  PermissionConfig,
  PermissionConfigItem,
  PermissionConfigOption,
} from '@repo/shared/interfaces';

export * from '@repo/ui/types';
