export enum Secrets {
  DB_URL = 'DB_URL',
  FIREBASE_AUTH_BASE_64 = 'FIREBASE_AUTH_BASE_64',
  SERVER_ENV = 'SERVER_ENV',
  NODE_ENV = 'NODE_ENV',
  PRIVATE_API_KEY = 'PRIVATE_API_KEY',
  PORT = 'PORT',
  SERVER_BASE_URL = 'SERVER_BASE_URL',
  FIREBASE_API_KEY = 'FIREBASE_API_KEY',
}
